run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,15 @@
 #!/bin/bash
-python3 <<< $PYFILE
+# Check if PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+	echo "Error: PYFILE environment variable is not set."
+	exit 1
+fi
+
+# Check if the specified file exists
+if [ ! -f "$PYFILE" ]; then
+	echo "Error: $PYFILE does not exist."
+	exit 1
+fi
+
+#run the python script
+python3 $PYFILE
